# Content of Will_McGowan_CV_Banking_PE_Consulting.pdf. Text is ReportLab paragraph markup: <b>, <i>, and &lt; for "<".
CV = {
  "name": "WILL McGOWAN",
  "contact": "Glasgow, UK | +44 7562 299 515 | mcgowanwill366@gmail.com",
  "sections": [
    {"title": "EDUCATION", "entries": [
      {"left": "<b>University of Strathclyde</b>, Glasgow", "right": "Sep 2023 – Jun 2027 (expected)",
       "rows": ["<i>BA (Hons) Economics</i>"],
       "bullets": ["Average grade to date: 2:1, including 90% in first-year Finance",
                   "Second-highest mark (78%) in a group project for Advanced Corporate Finance and Financial Markets",
                   "<b>Relevant Modules:</b> Treasury Management and Derivatives, Industrial Economics, Applied Econometrics"],
       "subs": [
         {"left": "<b>Dissertation</b> | <i>MATLAB</i>", "right": "In progress, due 2027",
          "rows": ["<i>“Who Hedges the Barrel? Sovereign Oil Hedging and Petro-Currency Reactions to OPEC News”</i>"],
          "bullets": ["Testing whether governments that hedge oil blunt their currencies’ reaction to OPEC news: Norway’s krone conversions (vs unhedged Canada), Russia’s 2017–22 budget rule and Mexico’s put hedge",
                      "Breaking the question into one testable prediction per country, using an original dataset from Norges Bank and the Russian and Mexican finance ministries, event studies and difference-in-differences"]},
         {"left": "<b>FX Risk Management</b> | <i>group project</i>", "right": "<i>Treasury Management and Derivatives</i>",
          "bullets": ["Mapped how six multinationals, including Toyota, Nestlé, NVIDIA and Reliance Industries, are exposed to currency risk through revenues and costs, then compared how each one manages it"]},
         {"left": "<b>Empirical CAPM Test</b>", "right": "<i>MATLAB</i>",
          "bullets": ["Tested the CAPM on 694 anomaly portfolios across 54 countries: it fails jointly in 48 of 53, and 123 of 215 apparent anomalies survive a correction for running so many tests, led by momentum and value"]},
         {"left": "<b>Monte Carlo Option Pricing Engine</b>", "right": "<i>MATLAB</i>",
          "bullets": ["Priced European and Asian options by simulation, benchmarked against Black-Scholes; a geometric-Asian control variate cut the arithmetic-Asian standard error by 97%, equivalent to 1,276 times as many paths"]},
       ]},
      {"left": "<b>Belfast Royal Academy</b>, Belfast", "right": "Jun 2023",
       "bullets": ["A-levels: Mathematics (A), Economics (A), Computer Science (B)"]},
    ]},
    {"title": "WORK EXPERIENCE", "entries": [
      {"left": "<b>Le Set</b>, Glasgow | <i>Head Mixologist</i>", "right": "Sep 2026 – Present",
       "bullets": ["Designed the 11-drink menu for a new 200-cover restaurant and cocktail lounge, including 4 original cocktails",
                   "Wrote batch specifications for 5 pre-batched cocktails and trained around 15 staff to serve them consistently"]},
      {"left": "<b>KONG</b>, Glasgow | <i>Mixologist and Front of House</i>", "right": "Oct 2024 – Jun 2026",
       "bullets": ["Analysed sales patterns to refine upselling prompts, raising average customer spend by an estimated 25%",
                   "Trained new staff on drink specifications, POS and licensing rules; reconciled cash and card takings each shift"]},
    ]},
    {"title": "LEADERSHIP AND ACTIVITIES", "entries": [
      {"left": "<b>Strathclyde Agricapital Society</b> | <i>Co-Founder and Treasurer</i>", "right": "Sep 2025 – Present",
       "bullets": ["Co-founded Strathclyde’s first agri-finance society, grew it to 126 members and wrote weekly research notes",
                   "Led weekly research sessions taking apart agribusiness deals such as SALIC’s USD&nbsp;1.24bn purchase of 35.4% of Olam Agri (implying USD&nbsp;3.5bn of equity): why this buyer, why now, structure and valuation",
                   "As Treasurer, manage the society’s budget and accounts"]},
      {"left": "<b>Strathclyde Poker Society</b> | <i>Vice-President, then President</i>", "right": "Sep 2025 – Apr 2026",
       "bullets": ["Ran weekly tournaments for about 60 players on a £600 budget per semester, reconciling buy-ins and prizes",
                   "Taught new members to use the Kelly criterion to estimate how many buy-ins their win rate, variance and risk level call for, with a buffer in case the edge is overestimated"]},
    ]},
    {"title": "ADDITIONAL INFORMATION", "paras": [
      "<b>Technical:</b> Excel, R, MATLAB, Git",
      "<b>Chess:</b> 14th at the 2023 Irish U19 Championships; played 22 opponents at once (average 1860 FIDE) and won 21",
      "<b>Powerlifting:</b> Northern Ireland U19 champion (2023)",
    ]},
  ],
}
